/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\sci-fi__future_tunnel.glb --transform 
Files: .\sci-fi__future_tunnel.glb [19.39MB] > C:\Users\jaind\Workshop\frontend\src\Models\sci-fi__future_tunnel-transformed.glb [2.03MB] (90%)
Author: nenkea (https://sketchfab.com/nenkea)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sci-fi-future-tunnel-07bdc493060c49d4b860e919fc2c47f0
Title: Sci-Fi / Future Tunnel
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import model from "./sci-fi__future_tunnel-transformed.glb"
export default function Model(props) {
  const { nodes, materials } = useGLTF(model)
  return (
    <group {...props} dispose={null} position={[0,0,0]}>
      {/* <ambientLight  intensity={1} /> */}
      <hemisphereLight   groundColor={"white"}  intensity={2} />

      {/* <directionalLight  */}
      <mesh geometry={nodes.Cube_Main_0.geometry} material={materials.Main} rotation={[-Math.PI / 2, 0, 0]} scale={0.112} />
      <mesh geometry={nodes.Cube_Beton_0.geometry} material={materials.Beton} rotation={[-Math.PI / 2, 0, 0]} scale={0.112} />
      <mesh geometry={nodes.Cube_Asphalt_0.geometry} material={materials.Asphalt} rotation={[-Math.PI / 2, 0, 0]} scale={0.112} />
      <mesh geometry={nodes.Cube_Klarer_Beton_0.geometry} material={materials.Klarer_Beton} rotation={[-Math.PI / 2, 0, 0]} scale={0.112} />
      <mesh geometry={nodes.Cube_Ganzstein_Schwarz_0.geometry} material={materials.Ganzstein_Schwarz} rotation={[-Math.PI / 2, 0, 0]} scale={0.112} />
      <mesh geometry={nodes.Cube_Metall_Dunkelbalu_0.geometry} material={materials.Metall_Dunkelbalu} rotation={[-Math.PI / 2, 0, 0]} scale={0.112} />
      <mesh geometry={nodes.Cube_Glas_0.geometry} material={materials.Glas} rotation={[-Math.PI / 2, 0, 0]} scale={0.112} />
      <mesh geometry={nodes.Cube_Beton_mit_Rillen_Bogen_0.geometry} material={materials.Beton_mit_Rillen_Bogen} rotation={[-Math.PI / 2, 0, 0]} scale={0.112} />
      <mesh geometry={nodes.Cube_Wandlichterhalter_0.geometry} material={materials.Wandlichterhalter} rotation={[-Math.PI / 2, 0, 0]} scale={0.112} />
      <mesh geometry={nodes.Cube_Wandlichter_0.geometry} material={materials.Wandlichter} rotation={[-Math.PI / 2, 0, 0]} scale={0.112} />
      <mesh geometry={nodes.Cube_Rand_0.geometry} material={materials.Rand} rotation={[-Math.PI / 2, 0, 0]} scale={0.112} />
      <mesh geometry={nodes.Cube_Streifen_0.geometry} material={materials.Streifen} rotation={[-Math.PI / 2, 0, 0]} scale={0.112} />
    </group>
  )
}

useGLTF.preload('/sci-fi__future_tunnel-transformed.glb')
